// contrib/views/k8s/src/main/resources/ui/src/App.tsx
/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// ui/src/App.tsx
import React from 'react';
import { HashRouter, Routes, Route, Navigate } from 'react-router-dom';
import { PermissionsProvider } from './context/PermissionsContext';
import { NamespaceProvider } from './context/NamespaceContext';
import { useClusterStatus } from './context/ClusterStatusContext';
import AppLayout from './components/layout/AppLayout';
import RepositoriesPage from './pages/HelmRepositoriesPage';
import GitRepositoriesPage from './pages/GitRepositoriesPage';
import DashboardPage from './pages/DashboardPage';
import NodesPage from './pages/NodesPage';
import HelmReleasesPage from './pages/HelmReleasesPage';
import ConfigurationPage from './pages/ConfigurationPage';
import WorkloadsPage from './pages/WorkloadsPage';
const CatalogPage = React.lazy(() => import('./pages/CatalogPage'));
const OperatorsPage = React.lazy(() => import('./pages/OperatorsPage'));
const TruststoresPage = React.lazy(() => import('./pages/TruststoresPage'));
const GlobalSecurityPage = React.lazy(() => import('./pages/GlobalSecurityPage'));
const GlobalConfigurationsPage = React.lazy(() => import('./pages/GlobalConfigurationsPage'));
const CertificateAuthoritiesPage = React.lazy(() => import('./pages/CertificateAuthoritiesPage'));
const ServiceWizardPage = React.lazy(() => import('./pages/ServiceWizardPage'));
import { Spin } from 'antd';
import '@ant-design/v5-patch-for-react-19';

/**
 * Main routing logic. Renders a stripped layout for the first-run
 * configuration screen and the full sidebar shell otherwise.
 */
const AppRouter: React.FC = () => {
  const { status } = useClusterStatus();
  if (status === 'loading') {
    return <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: '100vh' }}><Spin size="large" tip="Loading Configuration..." /></div>;
  }

  if (status === 'unconfigured') {
    return (
      <Routes>
        <Route path="/configuration" element={<ConfigurationPage />} />
        <Route path="*" element={<Navigate to="/configuration" replace />} />
      </Routes>
    );
  }

  return (
    <AppLayout>
      <Routes>
        <Route path="/" element={<DashboardPage />} />
        <Route path="/catalog" element={<React.Suspense fallback={<Spin />}><CatalogPage /></React.Suspense>} />
        <Route path="/nodes" element={<NodesPage />} />
        <Route path="/helm" element={<HelmReleasesPage />} />
        <Route path="/services/:serviceName" element={<React.Suspense fallback={<Spin />}><ServiceWizardPage /></React.Suspense>} />
        <Route path="/configuration" element={<ConfigurationPage />} />
        <Route path="/global-security" element={<React.Suspense fallback={<Spin />}><GlobalSecurityPage /></React.Suspense>} />
        <Route path="/certificate-authorities" element={<React.Suspense fallback={<Spin />}><CertificateAuthoritiesPage /></React.Suspense>} />
        <Route path="/truststores" element={<React.Suspense fallback={<Spin />}><TruststoresPage /></React.Suspense>} />
        <Route path="/operators" element={<React.Suspense fallback={<Spin />}><OperatorsPage /></React.Suspense>} />
        <Route path="/managed-configs" element={<React.Suspense fallback={<Spin />}><GlobalConfigurationsPage /></React.Suspense>} />
        <Route path="/workloads" element={<WorkloadsPage />} />
        <Route path="/repositories" element={<RepositoriesPage />} />
        <Route path="/git-repositories" element={<GitRepositoriesPage />} />
        <Route path="*" element={<Navigate to="/" replace />} />
      </Routes>
    </AppLayout>
  );
};

const App: React.FC = () => {
  return (
    <PermissionsProvider>
      <NamespaceProvider>
        <HashRouter>
          <AppRouter />
        </HashRouter>
      </NamespaceProvider>
    </PermissionsProvider>
  );
};

export default App;

// ambari-logsearch/ambari-logsearch-web/src/app/components/app.component.ts
/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Component, OnInit, OnDestroy } from '@angular/core';
import { Observable } from 'rxjs/Observable';
import { Subject } from 'rxjs/Subject';

import { Options } from 'angular2-notifications/src/options.type';

import { AppStateService } from '@app/services/storage/app-state.service';
import { DataAvailabilityValues } from '@app/classes/string';
import { notificationIcons } from '@modules/shared/services/notification.service';

import { Store } from '@ngrx/store';
import { AppStore } from '@app/classes/models/store';
import { AuthorizationStatuses } from '@app/store/reducers/auth.reducers';
import { isAuthorizedSelector, selectAuthStatus, isCheckingAuthStatusInProgressSelector } from '@app/store/selectors/auth.selectors';

import { HttpClientService } from '@app/services/http-client.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.less', '../modules/shared/notifications.less'],
  host: {
    '[class]': 'hostCssClasses'
  }
})
export class AppComponent implements OnInit, OnDestroy {

  authorizationStatuses = AuthorizationStatuses;

  isAuthorized$: Observable<boolean> = this.store.select(isAuthorizedSelector);
  authorizationStatus$: Observable<AuthorizationStatuses> = this.store.select(selectAuthStatus);
  isCheckingAuthStatusInProgress$: Observable<boolean> = this.store.select(isCheckingAuthStatusInProgressSelector);
  authorizationCode$: Observable<number> = this.appState.getParameter('authorizationCode');
  isBaseDataAvailable$: Observable<boolean> = this.appState.getParameter('baseDataSetState')
    .map((dataSetState: DataAvailabilityValues) => dataSetState === DataAvailabilityValues.AVAILABLE);

  destroyed$ = new Subject();

  notificationServiceOptions: Options = {
    timeOut: 2000,
    showProgressBar: true,
    pauseOnHover: true,
    preventLastDuplicates: 'visible',
    theClass: 'app-notification',
    icons: notificationIcons,
    position: ['top', 'left']
  };

  hostCssClasses = '';

  constructor(
    private appState: AppStateService,
    public httpClient: HttpClientService,
    private store: Store<AppStore>
  ) {}

  ngOnInit() {
    this.authorizationStatus$.distinctUntilChanged().takeUntil(this.destroyed$).subscribe(this.onAuthStatusChange);
  }

  ngOnDestroy() {
    this.destroyed$.next(true);
  }

  onAuthStatusChange = (status: AuthorizationStatuses): void => {
    this.setHostCssClasses(status ? status.replace(/\s/, '-').toLocaleLowerCase() : '');
  }

  setHostCssClasses(cls: string) {
    this.hostCssClasses = cls;
  }

}

<!--
  Licensed to the Apache Software Foundation (ASF) under one or more
  contributor license agreements.  See the NOTICE file distributed with
  this work for additional information regarding copyright ownership.
  The ASF licenses this file to You under the Apache License, Version 2.0
  (the "License"); you may not use this file except in compliance with
  the License.  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->

<header>
  <nav class="navbar" [class.authorized]="isAuthorized$ | async">
    <h1>{{'common.title' | translate}}</h1>
    <breadcrumbs *ngIf="(isAuthorized$ | async) && (isBaseDataAvailable$ | async)"></breadcrumbs>
    <top-menu *ngIf="(isAuthorized$ | async) && (isBaseDataAvailable$ | async)"></top-menu>
  </nav>
</header>

<ng-container *ngIf="(authorizationStatus$ | async) !== authorizationStatuses.LOGGED_OUT">
  <data-loading-indicator *ngIf="!(isBaseDataAvailable$ | async) && (isAuthorized$ | async)"></data-loading-indicator>

  <ng-container *ngIf="!(isAuthorized$ | async) || (isBaseDataAvailable$ | async)">
    <main-container></main-container>
    <user-settings *ngIf="(isAuthorized$ | async)"></user-settings>
    <timezone-picker *ngIf="(isAuthorized$ | async)"></timezone-picker>
  </ng-container>

  <simple-notifications [options]="notificationServiceOptions"></simple-notifications>
  <div class="request-indicator" [class.open]="httpClient.requestInProgress | async">
    <i class="fa fa-spin fa-gear"></i>
    {{ 'common.loading' | translate }}
  </div>
</ng-container>
